name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
      - name: Step two

  job2:
    name: Second job
    runs-on: windows-latest
      - name: Step one
      - name: Step two
